# -----------------------------------------------------------------------------
# Modules
# -----------------------------------------------------------------------------
# list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules)


# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------

get_filename_component(OT_SEC_FILE_TRANSFER_PROJECT_DIR "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

set(PROJ_SOVERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR})
set(PROJ_BUILDVERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})

# -----------------------------------------------------------------------------
# Directories
# -----------------------------------------------------------------------------

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/static_lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})

# directory for autogenerated configs
set(OT_SEC_FILE_TRANSFER_AUTOGEN_DIR ${CMAKE_BINARY_DIR}/autogen/ot-joinserver)
file(MAKE_DIRECTORY ${OT_SEC_FILE_TRANSFER_AUTOGEN_DIR})

# -----------------------------------------------------------------------------
# Dependencies
# -----------------------------------------------------------------------------
if(WITH_GOOGLE_TEST)
  find_package(GTest QUIET)
  if(NOT GTest_FOUND)
    include(FetchContent)
    FetchContent_Declare(
            googletest
            URL https://github.com/google/googletest/archive/refs/tags/v1.14.0.zip
        )
    # Keep GoogleTest from overriding project compiler/linker settings.
    set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
    FetchContent_MakeAvailable(googletest)
  endif()
endif()

if(POLICY CMP0167)
  cmake_policy(SET CMP0167 NEW)
endif()
# Boost.JSON: meta.json / manifest.json in transaction, request bodies in api.
# Boost.Beast / Boost.Asio (api, net) are header-only -> Boost::headers;
# 1.83+ for asio::as_tuple with C++20 coroutines.
# Boost.ProgramOptions: command line of the ftc client.
find_package(Boost 1.83 REQUIRED COMPONENTS json program_options)
if(NOT Boost_FOUND)
  message(FATAL_ERROR "Boost library not found")
endif()

# SHA-256 in common (OpenSSL::Crypto); TLS in api/net (OpenSSL::SSL).
find_package(OpenSSL REQUIRED)
find_package(toml11 CONFIG REQUIRED)

# Thread pool of the api server, TechLog writer thread.
find_package(Threads REQUIRED)


# -----------------------------------------------------------------------------
# Generating config files
# -----------------------------------------------------------------------------

configure_file(${OT_SEC_FILE_TRANSFER_PROJECT_DIR}/cmake/configs/version_constants.hpp.in ${OT_SEC_FILE_TRANSFER_AUTOGEN_DIR}/version_constants.hpp @ONLY)
